### ISSUE TITLE
[이슈] 로케일 가져오는 방식 선택

### ISSUE THREAD

**Issue by ChoMinGi** [Step3-kakao-tech-campus/Team4_FE#81]
## 이슈 개요
현재 저희 프로젝트 애플리케이션의 다국어 지원을 위해 적절한 로케일 해석 방식을 결정하고 구현할 필요가 있습니다.

## 배경
현재 애플리케이션은 다양한 국가와 언어를 사용하는 사용자들을 대상으로 서비스를 제공하고 있습니다. 이에 따라 사용자의 언어 및 지역 설정에 맞추어 콘텐츠를 제공하는 것이 중요합니다. 하지만 현재는 고정된 언어로만 서비스를 제공하고 있어 사용자 경험 개선이 필요합니다.

## 선택 요청 사항
- 사용자의 언어 및 지역 설정을 자동으로 감지하고 적용할 수 있는 기능이 필요합니다.
- 사용자가 직접 언어를 선택할 수 있는 기능이 포함되어야 합니다.
- 선택한 로케일 설정이 사용자의 세션 또는 쿠키에 저장되어 일관된 사용자 경험을 제공해야 합니다.
- 모바일과 데스크탑 환경 모두에서 원활하게 작동해야 합니다.

## 제안하는 해결 방안
스프링 부트에서 제공하는 여러 로케일 해석 방식 중 하나를 선택하고 구현하는 것을 제안합니다. 가능한 옵션은 다음과 같습니다.

- AcceptHeaderLocaleResolver (Header Resolver)
- CookieLocaleResolver
- SessionLocaleResolver
- FixedLocaleResolver
- LocaleChangeInterceptor와 함께 사용

프론트엔드 팀에서 이 중 하나를 선택하거나, 복합적인 접근 방식을 고려해주시기 바랍니다.

## 대안
프론트엔드에서 추가적인 처리가 필요 없는 AcceptHeaderLocaleResolver를 기본으로 하되, 사용자가 언어를 선택할 수 있는 기능을 추가하는 방법도 있습니다. 이 경우, 선택된 언어는 쿠키 또는 세션에 저장할 수 있습니다.

## 추가적인 컨텍스트
이 기능의 구현은 사용자 경험을 크게 향상시킬 수 있으며, 국제적인 사용자 기반으로 하는 저희 어플리케이션 특성상 중요한 역할을 할 것입니다.

## 백로그 정보
예상 작업 시간: 1주일

## 관련된 이슈
위 내용을 기반으로 프론트엔드 팀과 협의하여 최적의 방안을 결정하고자 합니다.

**Comment by ChoMinGi** [comment]
@HENOZIWD @coririri 
선택 부탁드립니다!

**Comment by ChoMinGi** [comment]
비회원의 경우에도 로케일 설정과 변경을 위해서라면 쿠키나 세션으로의 구현이 필요하다고 생각합니다.

**Comment by HENOZIWD** [comment]
현재 프론트에서
언어 감지 [i18next-browser-languageDetector](https://github.com/i18next/i18next-browser-languageDetector) 라이브러리 사용하고 있습니다.
언어 설정 [react-i18next](https://github.com/i18next/react-i18next) 라이브러리 사용하고 있습니다.
CSR 환경에서는 잘 동작하는데 SSR 환경에서는 어떨지 잘 모르겠네요.

제안해주신 방법 찾아봤는데 쿠키 활용하는게 가장 좋아 보입니다.
프론트에서 쿠키 생성해두면 서버에서 읽고 그에 맞는 컨텐츠 제공 <- 제가 이해한게 맞나요?

**Comment by coririri** [comment]
- 자동 감지 부분은 어떻게 구현해야 할지 아직 모르겠네요
- 현재 렌딩 페이지에서 사용자가 언어 선택하고, 하단 네이게이션 바에서 언어 선택 가능한 모달 창을 띄우는 버튼을 만들어둬도 좋을꺼 같네요
- AcceptHeaderLocaleResolver (Header Resolver) 방식으로 진행하면: 사용자 언어 정보를 쿠키에 담아 매 요청시 request header에 추가해서 api요청 하면 언어에 맞는 정보가 담겨 옴. (이렇게 이해 하면 될까요?)

**Comment by ChoMinGi** [comment]
@HENOZIWD 

> 현재 프론트에서
> 언어 감지 [i18next-browser-languageDetector](https://github.com/i18next/i18next-browser-languageDetector) 라이브러리 사용하고 있습니다.
> 언어 설정 [react-i18next](https://github.com/i18next/react-i18next) 라이브러리 사용하고 있습니다.
> CSR 환경에서는 잘 동작하는데 SSR 환경에서는 어떨지 잘 모르겠네요.
> 
> 제안해주신 방법 찾아봤는데 쿠키 활용하는게 가장 좋아 보입니다.
> 프론트에서 쿠키 생성해두면 서버에서 읽고 그에 맞는 컨텐츠 제공 <- 제가 이해한게 맞나요?

넵 맞습니다 제공할 언어만 따로 properties에 지정을 해놓으셨더라고요.

react-i18next CSR환경이네요! 그럼 다국어작업 구현이 완료되셨나요? Json형식으로 컴포넌트 따로 보여주는 작업 완료하셨다면 해당기능은 고려하지 않아도됩니다

**Comment by ChoMinGi** [comment]
> - 자동 감지 부분은 어떻게 구현해야 할지 아직 모르겠네요
브라우저에서 제공해주는 사항이라합니다


> - 현재 렌딩 페이지에서 사용자가 언어 선택하고, 하단 네이게이션 바에서 언어 선택 가능한 모달 창을 띄우는 버튼을 만들어둬도 좋을꺼 같네요
이건 항상 lang에 설정값을 주는 방식으로 구현될것 같네요


> - AcceptHeaderLocaleResolver (Header Resolver) 방식으로 진행하면: 사용자 언어 정보를 쿠키에 담아 매 요청시 request header에 추가해서 api요청 하면 언어에 맞는 정보가 담겨 옴. (이렇게 이해 하면 될까요?)
이건 첫번째 방식입니다 쿠키에 로케일 정보를 담는건

**Comment by ChoMinGi** [comment]
@coririri 
> > - 자동 감지 부분은 어떻게 구현해야 할지 아직 모르겠네요

 브라우저에서 제공해주는 사항이라합니다



> > - 현재 렌딩 페이지에서 사용자가 언어 선택하고, 하단 네이게이션 바에서 언어 선택 가능한 모달 창을 띄우는 버튼을 만들어둬도 좋을꺼 같네요

이건 항상 lang에 설정값을 주는 방식으로 구현될것 같네요


> > - AcceptHeaderLocaleResolver (Header Resolver) 방식으로 진행하면: 사용자 언어 정보를 쿠키에 담아 매 요청시 request header에 추가해서 api요청 하면 언어에 맞는 정보가 담겨 옴. (이렇게 이해 하면 될까요?)

이건 첫번째 방식입니다 쿠키에 로케일 정보를 담는건 CookieLocaleResolver 방식입니다

**Comment by coririri** [comment]
> @coririri
> 
> > > * 자동 감지 부분은 어떻게 구현해야 할지 아직 모르겠네요
> 
> 브라우저에서 제공해주는 사항이라합니다
> 
> > > * 현재 렌딩 페이지에서 사용자가 언어 선택하고, 하단 네이게이션 바에서 언어 선택 가능한 모달 창을 띄우는 버튼을 만들어둬도 좋을꺼 같네요
> 
> 이건 항상 lang에 설정값을 주는 방식으로 구현될것 같네요
> 
> > > * AcceptHeaderLocaleResolver (Header Resolver) 방식으로 진행하면: 사용자 언어 정보를 쿠키에 담아 매 요청시 request header에 추가해서 api요청 하면 언어에 맞는 정보가 담겨 옴. (이렇게 이해 하면 될까요?)
> 
> 이건 첫번째 방식입니다 쿠키에 로케일 정보를 담는건 CookieLocaleResolver 방식입니다

**Comment by coririri** [comment]
> @coririri
> 
> > > * 자동 감지 부분은 어떻게 구현해야 할지 아직 모르겠네요
> 
> 브라우저에서 제공해주는 사항이라합니다
> - 예전에 나왔던 의견인 사용자가 입력하는 언어를 자동감지하자는 의미인줄 착각했습니다
> > > * 현재 렌딩 페이지에서 사용자가 언어 선택하고, 하단 네이게이션 바에서 언어 선택 가능한 모달 창을 띄우는 버튼을 만들어둬도 좋을꺼 같네요
> 
> 이건 항상 lang에 설정값을 주는 방식으로 구현될것 같네요
> - 넵 이렇게 구현 하면 되겠네요
> > > * AcceptHeaderLocaleResolver (Header Resolver) 방식으로 진행하면: 사용자 언어 정보를 쿠키에 담아 매 요청시 request header에 추가해서 api요청 하면 언어에 맞는 정보가 담겨 옴. (이렇게 이해 하면 될까요?)
> 
> 이건 첫번째 방식입니다 쿠키에 로케일 정보를 담는건 CookieLocaleResolver 방식입니다
> - 넵 이렇게 구현하면 될 것 같습니다

**Comment by coririri** [comment]
> > @coririri
> > > > * 자동 감지 부분은 어떻게 구현해야 할지 아직 모르겠네요
> > 
> > 
> > 브라우저에서 제공해주는 사항이라합니다
> > 예전에 나왔던 의견인 사용자가 입력하는 언어를 자동감지하자는 의미인줄 착각했습니다
> > > > * 현재 렌딩 페이지에서 사용자가 언어 선택하고, 하단 네이게이션 바에서 언어 선택 가능한 모달 창을 띄우는 버튼을 만들어둬도 좋을꺼 같네요
> > 
> > 
> > 이건 항상 lang에 설정값을 주는 방식으로 구현될것 같네요
> > 넵 이렇게 구현 하면 되겠네요
> > > > * AcceptHeaderLocaleResolver (Header Resolver) 방식으로 진행하면: 사용자 언어 정보를 쿠키에 담아 매 요청시 request header에 추가해서 api요청 하면 언어에 맞는 정보가 담겨 옴. (이렇게 이해 하면 될까요?)
> > 
> > 
> > 이건 첫번째 방식입니다 쿠키에 로케일 정보를 담는건 CookieLocaleResolver 방식입니다
> > 넵 이렇게 구현하면 될 것 같습니다

**Comment by coririri** [comment]
프론트에서 자동 번역하기로 결정해 Issue close합니다.
