### ISSUE TITLE
[기능 요청] 이미지 업로드 보안 강화를 위한 파일 검증 로직 구현

### ISSUE THREAD

**Issue by ChoMinGi** [Step3-kakao-tech-campus/Team4_FE#82]
## 기능 요청 개요
리뷰 이미지 업로드 과정에서 클라이언트 단에서 수행되는 파일 검증 로직을 구현해야 합니다. 이는 보안을 강화하고, 서버에 부적절하거나 악의적인 파일이 업로드되는 것을 방지하기 위함입니다.

## 배경
프론트단에서 제안해준 방식대로 리뷰 이미지 업로드 시, 서버는 클라이언트에게 Presigned URL을 제공하고, 클라이언트가 직접 S3에 이미지를 업로드하고 있는 플로우라고 설명할 수 있습니다.

 이 과정에서 클라이언트 단에서의 파일 검증이 없으면, 악의적인 사용자가 부적절한 파일을 업로드할 수 있어 보안상 문제가 발생할 수 있습니다.

## 요구 사항
- [x] 클라이언트 단에서 이미지 파일 형식 검증 로직 구현 (예: JPEG, PNG 등 지정된 형식만 허용)
- [x] 클라이언트 단에서 이미지 파일 크기 제한 로직 구현 (예: 최대 5MB)
- [x] 필요한 경우, 이미지 파일의 해상도 또는 치수 제한을 두는 로직 추가
- [x] 파일 검증 실패 시, 사용자에게 명확한 오류 메시지 제공

## 제안하는 해결 방안
- 프론트엔드 코드 내에서 파일 업로드 입력 필드의 변경 이벤트를 감지하고, 선택된 파일의 형식과 크기를 검증하는 로직을 구현합니다. 이를 통해 부적합한 파일이 선택되었을 때, 즉시 사용자에게 피드백을 제공하고, 업로드를 차단합니다.

## 대안
기존 MediaFile 형식으로 서버사이드 업로딩 방식

## 백로그 정보
예상 작업 시간: N/A

관련된 이슈:
https://github.com/Step3-kakao-tech-campus/Team4_BE/issues/73

**Comment by coririri** [comment]
구현 시 이미지 형식, 크기 제한두고 명확한 에러 메시지 띄우도록 하겠습니다.

**Comment by HENOZIWD** [comment]
파일 형식은 webp, jpeg, png 세 가지로, 크기는 5MB 이하로 제한하여 구현 내용 추가했습니다.
[커밋 내역](https://github.com/Step3-kakao-tech-campus/Team4_FE/pull/80/commits/0cf0e3a8290833d82a553837e8267357024e6a34)

**Comment by ChoMinGi** [comment]
@HENOZIWD 
커밋 잘 확인하였습니다. 백엔드 또한 크기 5MB 이하로 jpeg, png, heic 형식을 검증하는 로직을 추가하였는데요

아이폰 유저들을 위해서 heic 형태도 열어놔주시면 좋을것 같습니다. 서버사이드에서도 webp 허용하도록하겠습니다.

**Comment by HENOZIWD** [comment]
@ChoMinGi 
windows 환경에서 heic 파일 업로드 시 파일 타입을 인식하지 못 하고 빈 문자열이 반환됩니다.
https://stackoverflow.com/questions/69711219/why-do-heic-heif-files-have-a-blank-file-type-in-a-filelist

iOS나 macOS에서는 heic 형식의 파일을 업로드 할 때 자체적으로 jpeg 형식으로 변환을 해 주는 것 같으니
고려하지 않아도 큰 문제 없을 듯 한데 어떻게 생각하시나요?

**Comment by ChoMinGi** [comment]
흠,, 더 찾아보니 안드로이드 계열의 HEIF 도 문제가 된다하네요

https://github.com/nokiatech/heif/issues/76

일단 기능 개발에 우선을 두어 jpg jpeg webp 정도만 허용하고 나머지 형식에 대해서는 예외처리를 해주는게 좋다고 생각하는데 어떻게 생각하시나요?

**Comment by ChoMinGi** [comment]
> @HENOZIWD 커밋 잘 확인하였습니다. 백엔드 또한 크기 5MB 이하로 jpeg, png, heic 형식을 검증하는 로직을 추가하였는데요
https://github.com/Step3-kakao-tech-campus/Team4_BE/pull/78

**Comment by HENOZIWD** [comment]
@ChoMinGi 
네 그렇게 하면 문제 없을 듯 합니다.
